function G_GPS = G_GPS(Vx,Vy,Vz,x,y,z)
%G_GPS
%    G_GPS = G_GPS(Vx,Vy,Vz,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Mar-2023 18:27:42

G_GPS = [x;y;-z;Vx;Vy;-Vz];
