function H_baro = H_baro
%H_baro
%    H_baro = H_baro

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Mar-2023 18:27:41

H_baro = [0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
